### ISSUE TITLE
ModuleNotFoundError: No module named 'myconfig.config'

### ISSUE THREAD

**Issue by zhouxuefengaaa** [cl2227619761/AttFPN-Ovarian-Cancer#7]
ModuleNotFoundError: No module named 'myconfig.config'

**Comment by zhouxuefengaaa** [comment]
(tct) (base) luzhe@ubuntu:/repository7403/luzhe/projects-zy/AttFPN-Ovarian-Cancer-master$ ./launch.sh
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    from tools.voc_utils import get_custom_voc
  File "/repository7403/luzhe/projects-zy/AttFPN-Ovarian-Cancer-master/tools/voc_utils.py", line 18, in <module>
    from myconfig.config import OPT
ModuleNotFoundError: No module named 'myconfig.config'
